import IconCloud from "./ui/icon-cloud";

const slugs = [
  "javascript",
  "java",
  "react",
  "html5",
  "css3",
  "nodedotjs",
  "express",
  "oracle",
  "indexeddb",
  "nodejs",
  "firebase",
  "mongodb",
  "mysql",
  "linux",
  "bash",
  "seaborn",
  "llm",
  "ai",
  "ml",
  "deeplearning",
  "nlp",
  "computervision",
  "reinforcementlearning",
  "postman",
  "windows",
  "oop",
  "os",
  "cn",
  "restapi",
  "redux",
  "tailwindcss",
  "generativeai",
  "rag",
  "promptengineering",
  "softcomputing",
  "logisim",
  "verilog",
  "jupyter",
  "colab",
  "folium",
  "kaggle",
  "leetcode",
  "geeksforgeeks",
  "hackerrank",
  "codeforces",
  "codechef",
  "vjudge",
  "python",
  "atcoder",
  "cloudinary",
  "c",
  "c++",
  "thunderclient",
  "matlab",
  "scikit-learn",
  "knime",
  "tableau",
  "aws",
  "ciscopackettracer",
  "pytorch",
  "tensorflow",
  "keras",
  "openai",
  "chartdotjs",
  "threejs",
  "vite",
  "numpy",
  "pandas",
  "matplotlib",
  "vercel",
  "testinglibrary",
  "jest",
  "jquery",
  "bootstrap",
  "reactrouter",
  "angular",
  "cypress",
  "docker",
  "git",
  "scilab",
  "github",
  "flask",
  "fastapi",
  "gitlab",
  "visualstudiocode",
  "figma",
];

function IconCloudDemo() {
  return (
    <div className="relative flex size-full max-w-lg items-center justify-center overflow-hidden rounded-lg  px-20 pb-20 pt-8 bg-transparent">
      <IconCloud iconSlugs={slugs} />
    </div>
  );
}

export default IconCloudDemo;